language: python

python:
  - 3.7

install:
  - sudo apt-get install gfortran
  - python3 -mpip install matplotlib
  - pip install pandas
  - pip install imageio

script:
  - cd src/testing/ && ./run_test.sh && cd ../../
  - mkdir bld && cd bld/
  - cmake ..
  - make
  - ./tsunami_prog
  - python plot_tsunami.py
  - python plot_tsunami_parallel.py
